### ISSUE TITLE
Uhm achtually its Caesar not Ceasar 🤓

### ISSUE THREAD

**Issue by Kliiyu** [VaagenIM/piggy#77]
"Oppgave 10 - Ceasar Cipher Enkryptering" L bozo
[Problem](https://piggy.iktim.no/main/VG2/IT/Utvikling/Programmering_-_Utforske_Programmeringsspr%C3%A5k/PS_Level_2_-_Bruk_det_nye_spr%C3%A5ket)

**Comment by svHvidsten** [comment]
Fixed 👍💯
